import { createHash } from 'node:crypto';
import { upsertContents } from '../repositories/contentRepository.js';
import { normalizeContent } from './contentNormalizer.js';

const SOURCE = {
  provider: 'curated-cn',
  label: '中国真实内容精选',
  region: 'CN',
};

// Yi-to-count helper: "46.15亿" → 4_615_000_000
function yiToCount(yi) {
  return Math.round(Number(yi) * 100_000_000);
}

const CURATED_REAL_CONTENTS = {
  drama: [
    {
      title: '十八岁太奶奶驾到，重整家族荣耀',
      summary: '2025 年大女主家庭短剧，云合 2025 短剧正片有效播放 TOP30 年榜冠军，正片有效播放 46.15 亿。',
      tags: ['短剧', '大女主', '家庭', '重生'],
      actors: ['李柯以'],
      characters: ['太奶奶', '家族掌权人'],
      author: '红果短剧',
      ipName: '十八岁太奶奶驾到，重整家族荣耀',
      hotScore: 461500,
      realPlayCount: yiToCount(46.15),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-06-10',
    },
    {
      title: '盛夏芬德拉',
      summary: '建筑设计师周晟安与恐婚叛逆的白清枚因家族联姻被迫结合，从契约婚姻走向双向救赎。叙事以红糖水、雨天倾伞等生活化细节传递克制温柔；公开报道显示其于 2025 年 10 月冲至 30 亿播放量，并入选国家广播电视总局 2025 年第四季度优秀网络视听作品。',
      tags: ['短剧', '治愈爱情', '契约婚姻', '精品化'],
      actors: ['刘萧旭', '郭宇欣'],
      characters: ['周晟安', '白清枚'],
      author: '马厩制片厂',
      ipName: '盛夏芬德拉',
      hotScore: 300000,
      realPlayCount: yiToCount(30),
      sourceUrl: 'https://news.hsw.cn/system/2025/1014/1879132.shtml',
      releaseDate: '2025-09-20',
    },
    {
      title: '好一个乖乖女',
      summary: '2025 年都市情感短剧，由余茵、柯淳主演，云合 2025 短剧正片有效播放 42.28 亿。',
      tags: ['短剧', '都市情感', '女频', '爱情'],
      actors: ['余茵', '柯淳'],
      characters: ['乖乖女', '都市恋人'],
      author: '于今无量',
      ipName: '好一个乖乖女',
      hotScore: 422800,
      realPlayCount: yiToCount(42.28),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-02-03',
    },
    {
      title: '穿过荆棘拥抱你',
      summary: '2025 年剧情爱情短剧，由李梦然、澄芓主演，云合 2025 短剧正片有效播放 41.88 亿。',
      tags: ['短剧', '剧情爱情', '女性成长'],
      actors: ['李梦然', '澄芓'],
      characters: ['荆棘女主', '守护恋人'],
      author: '北京蜜芽文化传播有限公司',
      ipName: '穿过荆棘拥抱你',
      hotScore: 418800,
      realPlayCount: yiToCount(41.88),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-06-20',
    },
    {
      title: '顶级偏爱：妈咪，我找到爹地了',
      summary: '2025 年家庭伦理短剧，云合 2025 短剧正片有效播放 36.46 亿，位列年度正片有效播放前列。',
      tags: ['短剧', '家庭伦理', '萌宝', '都市'],
      actors: [],
      characters: ['妈咪', '爹地', '萌宝'],
      author: '红果短剧',
      ipName: '顶级偏爱：妈咪，我找到爹地了',
      hotScore: 364600,
      realPlayCount: yiToCount(36.46),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-01-20',
    },
    {
      title: '请君入我怀',
      summary: '2025 年宣斗宅斗题材短剧，由何聪睿、刘念主演，云合 2025 短剧正片有效播放 35.33 亿。',
      tags: ['短剧', '宣斗宅斗', '爱情'],
      actors: ['何聪睿', '刘念'],
      characters: ['宅斗女主', '权谋男主'],
      author: '红果短剧',
      ipName: '请君入我怀',
      hotScore: 353300,
      realPlayCount: yiToCount(35.33),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-03-20',
    },
    {
      title: '十八岁太奶奶驾到，重整家族荣耀第二部',
      summary: '《十八岁太奶奶驾到，重整家族荣耀》续作，云合 2025 短剧正片有效播放 35.24 亿。',
      tags: ['短剧', '大女主', '家庭', '续作'],
      actors: ['李柯以', '王培延', '吴添豪', '王道铁'],
      characters: ['太奶奶', '家族后辈'],
      author: '红果短剧',
      ipName: '十八岁太奶奶驾到，重整家族荣耀',
      hotScore: 352400,
      realPlayCount: yiToCount(35.24),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-07-25',
    },
    {
      title: '家里家外',
      summary: '2025 年川渝方言年代家庭群像短剧，云合 2025 短剧正片有效播放 31.38 亿。',
      tags: ['短剧', '年代家庭', '方言', '群像'],
      actors: [],
      characters: ['川渝母亲', '家庭群像'],
      author: '红果短剧',
      ipName: '家里家外',
      hotScore: 313800,
      realPlayCount: yiToCount(31.38),
      sourceUrl: 'https://www.sina.cn/news/detail/5252080035170627.html',
      releaseDate: '2025-03-14',
    },
    {
      title: '念念有词',
      summary: '2025 年都市情感短剧，云合 2025 短剧正片有效播放 28.15 亿。',
      tags: ['短剧', '都市情感', '先婚后爱'],
      actors: ['何聪睿', '刘念'],
      characters: ['念念', '先婚后爱男主'],
      author: '红果短剧',
      ipName: '念念有词',
      hotScore: 281500,
      realPlayCount: yiToCount(28.15),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-07-03',
    },
    {
      title: '荒年全村啃树皮，我有系统满仓肉',
      summary: '2025 年宣斗宅斗短剧，云合 2025 短剧正片有效播放 26.12 亿。',
      tags: ['短剧', '宣斗宅斗', '系统', '逆袭'],
      actors: [],
      characters: ['系统女主', '荒年村民'],
      author: '红果短剧',
      ipName: '荒年全村啃树皮，我有系统满仓肉',
      hotScore: 261200,
      realPlayCount: yiToCount(26.12),
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-05-07',
    },
    {
      title: '暗潮涌动',
      summary: '民国谍战短剧，主线围绕地下潜伏、情报博弈与信仰抉择展开。国家广播电视总局《2025年10月至12月全国国产网络剧片发行许可情况》可查其发行许可（（桂）网微剧审字（2025）第006号，重点微短剧 60 集）；公开播放总量待平台披露。',
      tags: ['短剧', '民国谍战', '悬疑', '刘萧旭'],
      actors: ['刘萧旭', '王小亿'],
      characters: ['潜伏者', '情报员'],
      author: '红果短剧',
      ipName: '暗潮涌动',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/module/download/downfile.jsp?classid=0&filename=900bf4649fba4437999f8aa3aadb7a8a.pdf&showname=1.2025%E5%B9%B410%E6%9C%88%E8%87%B312%E6%9C%88%E5%85%A8%E5%9B%BD%E5%9B%BD%E4%BA%A7%E7%BD%91%E7%BB%9C%E5%89%A7%E7%89%87%E5%8F%91%E8%A1%8C%E8%AE%B8%E5%8F%AF%E6%83%85%E5%86%B5.pdf',
      releaseDate: '2025-11-01',
    },
    {
      title: '无双',
      summary: '短剧爆款代表，常见发行口径按微短剧/短剧传播，不纳入长剧、电视剧或网剧；公开播放总量待平台披露。',
      tags: ['短剧', '逆袭', '爽文改编', '爆款'],
      actors: [],
      characters: ['无双战神', '逆袭男主'],
      author: '短剧平台',
      ipName: '无双',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/',
      releaseDate: '2023-01-01',
    },
    {
      title: '长路初心',
      summary: '现实题材反腐短剧，以 2007-2025 年跨度呈现主角在权力与欲望中的失守轨迹。国家广播电视总局《2025年10月至12月全国国产网络剧片发行许可情况》可查其发行许可（（川）网微剧审字（2025）第019号，重点微短剧 88 集）；公开播放总量待平台披露。',
      tags: ['短剧', '现实题材', '反腐', '刘萧旭'],
      actors: ['吴刚', '刘萧旭', '杨懿'],
      characters: ['反腐干部', '失守者'],
      author: '红果短剧',
      ipName: '长路初心',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/module/download/downfile.jsp?classid=0&filename=900bf4649fba4437999f8aa3aadb7a8a.pdf&showname=1.2025%E5%B9%B410%E6%9C%88%E8%87%B312%E6%9C%88%E5%85%A8%E5%9B%BD%E4%BA%A7%E7%BD%91%E7%BB%9C%E5%89%A7%E7%89%87%E5%8F%91%E8%A1%8C%E8%AE%B8%E5%8F%AF%E6%83%85%E5%86%B5.pdf',
      releaseDate: '2026-01-10',
    },
    {
      title: '闪婚后，傅先生马甲藏不住了',
      summary: '2025 年都市甜宠短剧，闪婚设定下隐藏身份逐一揭晓，播放量超 25 亿。',
      tags: ['短剧', '甜宠', '闪婚', '马甲'],
      actors: ['马倩倩', '张星特'],
      characters: ['傅先生', '闪婚女主'],
      author: '九州短剧',
      ipName: '闪婚后，傅先生马甲藏不住了',
      hotScore: 250000,
      realPlayCount: yiToCount(25),
      sourceUrl: '',
      releaseDate: '2025-04-15',
    },
    {
      title: '重生之都市仙尊',
      summary: '2025 年都市重生短剧，仙尊陨落重生都市，以无敌修为守护家人、横扫一切不服，播放量突破 20 亿。',
      tags: ['短剧', '都市', '重生', '仙尊'],
      actors: ['张星特', '马倩倩'],
      characters: ['仙尊', '都市守护者'],
      author: '九州短剧',
      ipName: '重生之都市仙尊',
      hotScore: 200000,
      realPlayCount: yiToCount(20),
      sourceUrl: '',
      releaseDate: '2025-03-20',
    },
    {
      title: '顾少的隐婚罪妻',
      summary: '2025 年虐恋短剧，隐婚妻子在误会与伤害中挣扎求生，最终赢得真爱与尊严，播放量超 18 亿。',
      tags: ['短剧', '虐恋', '隐婚', '逆袭'],
      actors: ['申浩男', '王格格'],
      characters: ['顾少', '隐婚妻子'],
      author: '红果短剧',
      ipName: '顾少的隐婚罪妻',
      hotScore: 180000,
      realPlayCount: yiToCount(18),
      sourceUrl: '',
      releaseDate: '2025-05-10',
    },
    {
      title: '逆袭之星途璀璨',
      summary: '2025 年娱乐圈逆袭短剧，小透明艺人凭实力逆风翻盘、登顶影后，播放量超 15 亿。',
      tags: ['短剧', '娱乐圈', '逆袭', '女性成长'],
      actors: ['余茵', '柯淳'],
      characters: ['小透明艺人', '影帝男主'],
      author: '于今无量',
      ipName: '逆袭之星途璀璨',
      hotScore: 150000,
      realPlayCount: yiToCount(15),
      sourceUrl: '',
      releaseDate: '2025-08-01',
    },
    {
      title: '我在八零年代当后妈',
      summary: '2025 年年代穿越短剧，现代女主穿越到 80 年代成为后妈，用智慧经营家庭与事业，播放量超 12 亿。',
      tags: ['短剧', '年代', '穿越', '后妈'],
      actors: ['李柯以', '王培延'],
      characters: ['穿越后妈', '年代丈夫'],
      author: '红果短剧',
      ipName: '我在八零年代当后妈',
      hotScore: 120000,
      realPlayCount: yiToCount(12),
      sourceUrl: '',
      releaseDate: '2025-02-14',
    },
    {
      title: '错撩',
      summary: '2025 年都市甜宠短剧，误撩总裁引发甜蜜纠葛，轻喜剧风格深受观众喜爱，播放量超 10 亿。',
      tags: ['短剧', '甜宠', '轻喜剧', '总裁'],
      actors: ['何聪睿', '刘念'],
      characters: ['误撩女主', '总裁男主'],
      author: '红果短剧',
      ipName: '错撩',
      hotScore: 100000,
      realPlayCount: yiToCount(10),
      sourceUrl: '',
      releaseDate: '2025-06-01',
    },
    {
      title: '替嫁新娘：慕少的心尖宠',
      summary: '2025 年替嫁甜宠短剧，替嫁妹妹意外获得豪门真爱，播放量超 8 亿。',
      tags: ['短剧', '替嫁', '甜宠', '豪门'],
      actors: [],
      characters: ['替嫁新娘', '慕少'],
      author: '红果短剧',
      ipName: '替嫁新娘：慕少的心尖宠',
      hotScore: 80000,
      realPlayCount: yiToCount(8),
      sourceUrl: '',
      releaseDate: '2025-04-20',
    },
  ],
  novel: [
    {
      title: '斗破苍穹',
      summary: '天蚕土豆创作的玄幻网文代表作，公开传播口径多按百亿级累计阅读量统计。',
      tags: ['玄幻', '网文', '爽文'],
      actors: ['天蚕土豆'],
      characters: ['萧炎', '药老', '美杜莎'],
      author: '天蚕土豆',
      ipName: '斗破苍穹',
      hotScore: 1_000_000,
      realReadCount: yiToCount(100),
      sourceUrl: 'https://www.cbish.com/xue/35826.html',
      releaseDate: '2009-04-14',
    },
    {
      title: '凡人修仙传',
      summary: '忘语创作的仙侠小说，“凡人流”开创文本，公开报道显示原著累计阅读量超百亿。',
      tags: ['仙侠', '修仙', '网文'],
      actors: ['忘语'],
      characters: ['韩立', '南宫婉'],
      author: '忘语',
      ipName: '凡人修仙传',
      hotScore: 1_000_000,
      realReadCount: yiToCount(100),
      sourceUrl: 'https://finance.sina.cn/2025-08-21/detail-infmsqmp9833508.d.html?from=qudao',
      releaseDate: '2008-02-01',
    },
    {
      title: '全职高手',
      summary: '蝴蝶蓝创作的电竞网文代表作，公开传播口径多按百亿级累计阅读量归纳。',
      tags: ['电竞', '热血', '网文'],
      actors: ['蝴蝶蓝'],
      characters: ['叶修', '苏沐橙'],
      author: '蝴蝶蓝',
      ipName: '全职高手',
      hotScore: 1_000_000,
      sourceUrl: 'https://www.nbd.com.cn/rss/toutiao/articles/1358685.html',
      releaseDate: '2011-02-01',
    },
    {
      title: '诡秘之主',
      summary: '爱潜水的乌贼创作的蒸汽朋克奇幻网文，中文累计阅读量公开披露有限，这里按保守可确认口径入库。',
      tags: ['奇幻', '克苏鲁', '网文'],
      actors: ['爱潜水的乌贼'],
      characters: ['克莱恩', '奥黛丽'],
      author: '爱潜水的乌贼',
      ipName: '诡秘之主',
      hotScore: 10_000,
      sourceUrl: 'https://www.lomworld.com/zh/news/4',
      releaseDate: '2018-04-01',
    },
    {
      title: '三体',
      summary: '刘慈欣创作的中国科幻长篇，公开资料主要披露全球销量超过 3000 万册，累计阅读量待平台披露。',
      tags: ['科幻', '雨果奖', '硬科幻'],
      actors: ['刘慈欣'],
      characters: ['叶文洁', '罗辑', '程心'],
      author: '刘慈欣',
      ipName: '三体',
      hotScore: 0,
      sourceUrl: 'https://www.stdaily.com/web/gdxw/2025-08/24/content_389669.html',
      releaseDate: '2008-01-01',
    },
    {
      title: '庆余年',
      summary: '猫腻创作的架空历史小说，剧集热播期带动起点专区亿级流量，原著累计阅读量未公开披露。',
      tags: ['架空历史', '权谋', '网文'],
      actors: ['猫腻'],
      characters: ['范闲', '庆帝'],
      author: '猫腻',
      ipName: '庆余年',
      hotScore: 0,
      sourceUrl: 'https://news.cnhubei.com/content/2024-06/09/content_18025389.html',
      releaseDate: '2007-01-01',
    },
    {
      title: '盗墓笔记',
      summary: '南派三叔创作的冒险悬疑小说，公开资料主要披露实体书销量，累计阅读量待平台披露。',
      tags: ['悬疑', '冒险', '盗墓'],
      actors: ['南派三叔'],
      characters: ['吴邪', '张起灵', '王胖子'],
      author: '南派三叔',
      ipName: '盗墓笔记',
      hotScore: 0,
      sourceUrl: 'https://www.chinanews.com.cn/cul/2011/11-24/3482487.shtml',
      releaseDate: '2006-07-01',
    },
    {
      title: '鬼吹灯',
      summary: '天下霸唱创作的探险小说，公开资料主要披露图书销量与读者群，累计阅读量待平台披露。',
      tags: ['探险', '悬疑', '民俗'],
      actors: ['天下霸唱'],
      characters: ['胡八一', '王胖子', 'Shirley杨'],
      author: '天下霸唱',
      ipName: '鬼吹灯',
      hotScore: 0,
      sourceUrl: 'https://media.people.com.cn/n/2015/0913/c40606-27576269.html',
      releaseDate: '2006-01-01',
    },
    {
      title: '大奉打更人',
      summary: '卖报小郎君创作的仙侠探案网文，公开资料披露剧集、有声和改编表现较多，小说累计阅读量待平台披露。',
      tags: ['仙侠', '探案', '网文'],
      actors: ['卖报小郎君'],
      characters: ['许七安', '怀庆'],
      author: '卖报小郎君',
      ipName: '大奉打更人',
      hotScore: 0,
      sourceUrl: 'https://xueqiu.com/6899105006/362778550',
      releaseDate: '2020-06-01',
    },
    {
      title: '雪中悍刀行',
      summary: '烽火戏诸侯创作的武侠玄幻小说，公开资料多披露影视播放量与 IP 榜单，原著累计阅读量待平台披露。',
      tags: ['武侠', '玄幻', '网文'],
      actors: ['烽火戏诸侯'],
      characters: ['徐凤年', '姜泥'],
      author: '烽火戏诸侯',
      ipName: '雪中悍刀行',
      hotScore: 0,
      sourceUrl: 'https://www.jiemian.com/article/6983928.html',
      releaseDate: '2012-12-01',
    },
    {
      title: '斗罗大陆',
      summary: '唐家三少创作的玄幻网文代表作，讲述唐三在斗罗大陆的修炼与冒险，公开口径统计累计阅读量超百亿。',
      tags: ['玄幻', '网文', '修炼'],
      actors: ['唐家三少'],
      characters: ['唐三', '小舞', '戴沐白'],
      author: '唐家三少',
      ipName: '斗罗大陆',
      hotScore: 900000,
      realReadCount: yiToCount(100),
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2008-12-01',
    },
    {
      title: '遮天',
      summary: '辰东创作的仙侠玄幻网文，九龙拉棺开篇震撼读者，公开口径统计累计阅读量超数十亿。',
      tags: ['仙侠', '玄幻', '网文'],
      actors: ['辰东'],
      characters: ['叶凡', '姬紫月', '庞博'],
      author: '辰东',
      ipName: '遮天',
      hotScore: 800000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2010-10-01',
    },
    {
      title: '完美世界',
      summary: '辰东创作的玄幻网文，讲述石昊从荒域走向巅峰的热血征途，累计阅读量数十亿级。',
      tags: ['玄幻', '网文', '热血'],
      actors: ['辰东'],
      characters: ['石昊', '清漪', '火灵儿'],
      author: '辰东',
      ipName: '完美世界',
      hotScore: 750000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2013-08-01',
    },
    {
      title: '仙逆',
      summary: '耳根创作的仙侠网文，以王林逆天改命的修仙之路为核心，口碑与热度兼具。',
      tags: ['仙侠', '网文', '逆袭'],
      actors: ['耳根'],
      characters: ['王林', '李慕婉'],
      author: '耳根',
      ipName: '仙逆',
      hotScore: 600000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2009-06-01',
    },
    {
      title: '牧神记',
      summary: '宅猪创作的玄幻网文，讲述秦牧在残老村成长、开辟新道的传奇故事，起点均订超万。',
      tags: ['玄幻', '网文', '成长'],
      actors: ['宅猪'],
      characters: ['秦牧', '司婆婆', '村长'],
      author: '宅猪',
      ipName: '牧神记',
      hotScore: 500000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2017-06-01',
    },
    {
      title: '诡秘之主2：宿命之环',
      summary: '爱潜水的乌贼创作的诡秘之主续作，延续蒸汽朋克与克苏鲁风格，连载热度极高。',
      tags: ['奇幻', '克苏鲁', '网文'],
      actors: ['爱潜水的乌贼'],
      characters: ['卢米安', '奥萝尔'],
      author: '爱潜水的乌贼',
      ipName: '诡秘之主2：宿命之环',
      hotScore: 400000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2023-03-01',
    },
    {
      title: '深空彼岸',
      summary: '辰东创作的都市玄幻网文，融合科幻与修仙元素，讲述许长生在异变时代的崛起之路。',
      tags: ['玄幻', '都市', '网文'],
      actors: ['辰东'],
      characters: ['许长生', '王煊'],
      author: '辰东',
      ipName: '深空彼岸',
      hotScore: 350000,
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2021-09-01',
    },
    {
      title: '夜的命名术',
      summary: '会说话的肘子创作的都市异能网文，以群像叙事和时间循环为核心设定，累计阅读量超十亿。',
      tags: ['都市', '异能', '网文'],
      actors: ['会说话的肘子'],
      characters: ['林守溪', '白月初'],
      author: '会说话的肘子',
      ipName: '夜的命名术',
      hotScore: 300000,
      realReadCount: yiToCount(10),
      sourceUrl: 'https://www.qidian.com/',
      releaseDate: '2022-04-01',
    },
  ],

};

const CURATED_REAL_TITLES_BY_TYPE = new Map(
  Object.entries(CURATED_REAL_CONTENTS).map(([type, items]) => [
    type,
    new Set(items.map(item => item.title)),
  ])
);

function isCuratedRealSeedEnabled(value = process.env.MEDIAHUB_CURATED_REAL_SEED_ENABLED) {
  const normalized = String(value ?? '').trim().toLowerCase();
  if (!normalized) return true;
  return ['1', 'true', 'yes', 'on'].includes(normalized);
}

function buildCuratedId(type, title) {
  const hash = createHash('sha1').update(`${type}:${title}`).digest('hex').slice(0, 12);
  return `${type}:curated-cn:${hash}`;
}

function buildCuratedRealContents(type) {
  const metricField = type === 'novel' || type === 'comic' ? 'realReadCount' : 'realPlayCount';
  return (CURATED_REAL_CONTENTS[type] || []).map(item => {
    const realCount = Number(item.realPlayCount || item.realReadCount) || 0;
    const metrics = {};
    if (realCount > 0) {
      metrics[metricField] = realCount;
      metrics.realMetricStatus = 'official';
      metrics.realMetricCapturedAt = item.releaseDate ? new Date(item.releaseDate).toISOString() : new Date().toISOString();
      metrics.realMetricSources = [{
        sourceId: 'curated-cn',
        sourceName: SOURCE.label,
        sourceUrl: item.sourceUrl || '',
        metricType: metricField === 'realReadCount' ? 'read' : 'play',
        value: realCount,
        unit: 'count',
        method: 'public_page',
        confidence: 'official',
        capturedAt: metrics.realMetricCapturedAt,
      }];
    }
    return normalizeContent({
      id: buildCuratedId(type, item.title),
      title: item.title,
      summary: item.summary,
      type,
      tags: item.tags,
      actors: item.actors,
      characters: item.characters,
      author: item.author,
      ipName: item.ipName,
      status: 'completed',
      hotScore: item.hotScore,
      createdAt: item.releaseDate,
      updatedAt: item.releaseDate,
      source: {
        ...SOURCE,
        url: item.sourceUrl,
      },
      metrics,
    });
  });
}

function isCurrentCuratedChinaTitle(type, title) {
  return Boolean(CURATED_REAL_TITLES_BY_TYPE.get(type)?.has(title));
}

function getCuratedChinaFilterPairs() {
  return [...CURATED_REAL_TITLES_BY_TYPE.entries()].flatMap(([type, titles]) => (
    [...titles].map(title => ({ type, title }))
  ));
}

function seedCuratedRealContents(type) {
  const list = buildCuratedRealContents(type);
  if (list.length === 0) return { count: 0, list };
  return {
    count: upsertContents(list),
    list,
  };
}

function seedAllCuratedRealContents() {
  return Object.keys(CURATED_REAL_CONTENTS).map(type => ({
    type,
    ...seedCuratedRealContents(type),
  }));
}

export {
  buildCuratedRealContents,
  getCuratedChinaFilterPairs,
  isCuratedRealSeedEnabled,
  isCurrentCuratedChinaTitle,
  seedAllCuratedRealContents,
  seedCuratedRealContents,
};
