import { createHash } from 'node:crypto';
import { upsertContents } from '../repositories/contentRepository.js';
import { normalizeContent } from './contentNormalizer.js';

const SOURCE = {
  provider: 'curated-cn',
  label: '中国真实内容精选',
  region: 'CN',
};

const CURATED_REAL_CONTENTS = {
  drama: [
    {
      title: '十八岁太奶奶驾到，重整家族荣耀',
      summary: '2025 年大女主家庭短剧，云合 2025 短剧正片有效播放 TOP30 年榜冠军，正片有效播放 46.15 亿。',
      tags: ['短剧', '大女主', '家庭', '重生'],
      actors: ['李柯以'],
      author: '红果短剧',
      ipName: '十八岁太奶奶驾到，重整家族荣耀',
      hotScore: 461500,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-06-10',
    },
    {
      title: '盛夏芬德拉',
      summary: '建筑设计师周晟安与恐婚叛逆的白清枚因家族联姻被迫结合，从契约婚姻走向双向救赎。叙事以红糖水、雨天倾伞等生活化细节传递克制温柔；公开报道显示其于 2025 年 10 月冲至 30 亿播放量，并入选国家广播电视总局 2025 年第四季度优秀网络视听作品。',
      tags: ['短剧', '治愈爱情', '契约婚姻', '精品化'],
      actors: ['刘萧旭', '郭宇欣'],
      author: '马厩制片厂',
      ipName: '盛夏芬德拉',
      hotScore: 300000,
      sourceUrl: 'https://news.hsw.cn/system/2025/1014/1879132.shtml',
      releaseDate: '2025-09-20',
    },
    {
      title: '好一个乖乖女',
      summary: '2025 年都市情感短剧，由余茵、柯淳主演，云合 2025 短剧正片有效播放 42.28 亿。',
      tags: ['短剧', '都市情感', '女频', '爱情'],
      actors: ['余茵', '柯淳'],
      author: '于今无量',
      ipName: '好一个乖乖女',
      hotScore: 422800,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-02-03',
    },
    {
      title: '穿过荆棘拥抱你',
      summary: '2025 年剧情爱情短剧，由李梦然、澄芓主演，云合 2025 短剧正片有效播放 41.88 亿。',
      tags: ['短剧', '剧情爱情', '女性成长'],
      actors: ['李梦然', '澄芓'],
      author: '北京蜜芽文化传播有限公司',
      ipName: '穿过荆棘拥抱你',
      hotScore: 418800,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-06-20',
    },
    {
      title: '顶级偏爱：妈咪，我找到爹地了',
      summary: '2025 年家庭伦理短剧，云合 2025 短剧正片有效播放 36.46 亿，位列年度正片有效播放前列。',
      tags: ['短剧', '家庭伦理', '萌宝', '都市'],
      actors: [],
      author: '红果短剧',
      ipName: '顶级偏爱：妈咪，我找到爹地了',
      hotScore: 364600,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-01-20',
    },
    {
      title: '请君入我怀',
      summary: '2025 年宣斗宅斗题材短剧，由何聪睿、刘念主演，云合 2025 短剧正片有效播放 35.33 亿。',
      tags: ['短剧', '宣斗宅斗', '爱情'],
      actors: ['何聪睿', '刘念'],
      author: '红果短剧',
      ipName: '请君入我怀',
      hotScore: 353300,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-03-20',
    },
    {
      title: '十八岁太奶奶驾到，重整家族荣耀第二部',
      summary: '《十八岁太奶奶驾到，重整家族荣耀》续作，云合 2025 短剧正片有效播放 35.24 亿。',
      tags: ['短剧', '大女主', '家庭', '续作'],
      actors: ['李柯以', '王培延', '吴添豪', '王道铁'],
      author: '红果短剧',
      ipName: '十八岁太奶奶驾到，重整家族荣耀',
      hotScore: 352400,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-07-25',
    },
    {
      title: '家里家外',
      summary: '2025 年川渝方言年代家庭群像短剧，云合 2025 短剧正片有效播放 31.38 亿。',
      tags: ['短剧', '年代家庭', '方言', '群像'],
      actors: [],
      author: '红果短剧',
      ipName: '家里家外',
      hotScore: 313800,
      sourceUrl: 'https://www.sina.cn/news/detail/5252080035170627.html',
      releaseDate: '2025-03-14',
    },
    {
      title: '念念有词',
      summary: '2025 年都市情感短剧，云合 2025 短剧正片有效播放 28.15 亿。',
      tags: ['短剧', '都市情感', '先婚后爱'],
      actors: ['何聪睿', '刘念'],
      author: '红果短剧',
      ipName: '念念有词',
      hotScore: 281500,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-07-03',
    },
    {
      title: '荒年全村啃树皮，我有系统满仓肉',
      summary: '2025 年宣斗宅斗短剧，云合 2025 短剧正片有效播放 26.12 亿。',
      tags: ['短剧', '宣斗宅斗', '系统', '逆袭'],
      actors: [],
      author: '红果短剧',
      ipName: '荒年全村啃树皮，我有系统满仓肉',
      hotScore: 261200,
      sourceUrl: 'https://cj.sina.com.cn/articles/view/7879922982/1d5ae15260190aafeo?froms=ggmp',
      releaseDate: '2025-05-07',
    },
    {
      title: '暗潮涌动',
      summary: '民国谍战短剧，主线围绕地下潜伏、情报博弈与信仰抉择展开。国家广播电视总局《2025年10月至12月全国国产网络剧片发行许可情况》可查其发行许可（（桂）网微剧审字（2025）第006号，重点微短剧 60 集）；公开播放总量待平台披露。',
      tags: ['短剧', '民国谍战', '悬疑', '刘萧旭'],
      actors: ['刘萧旭', '王小亿'],
      author: '红果短剧',
      ipName: '暗潮涌动',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/module/download/downfile.jsp?classid=0&filename=900bf4649fba4437999f8aa3aadb7a8a.pdf&showname=1.2025%E5%B9%B410%E6%9C%88%E8%87%B312%E6%9C%88%E5%85%A8%E5%9B%BD%E5%9B%BD%E4%BA%A7%E7%BD%91%E7%BB%9C%E5%89%A7%E7%89%87%E5%8F%91%E8%A1%8C%E8%AE%B8%E5%8F%AF%E6%83%85%E5%86%B5.pdf',
      releaseDate: '2025-11-01',
    },
    {
      title: '无双',
      summary: '短剧爆款代表，常见发行口径按微短剧/短剧传播，不纳入长剧、电视剧或网剧；公开播放总量待平台披露。',
      tags: ['短剧', '逆袭', '爽文改编', '爆款'],
      actors: [],
      author: '短剧平台',
      ipName: '无双',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/',
      releaseDate: '2023-01-01',
    },
    {
      title: '长路初心',
      summary: '现实题材反腐短剧，以 2007-2025 年跨度呈现主角在权力与欲望中的失守轨迹。国家广播电视总局《2025年10月至12月全国国产网络剧片发行许可情况》可查其发行许可（（川）网微剧审字（2025）第019号，重点微短剧 88 集）；公开播放总量待平台披露。',
      tags: ['短剧', '现实题材', '反腐', '刘萧旭'],
      actors: ['吴刚', '刘萧旭', '杨懿'],
      author: '红果短剧',
      ipName: '长路初心',
      hotScore: 0,
      sourceUrl: 'https://www.nrta.gov.cn/module/download/downfile.jsp?classid=0&filename=900bf4649fba4437999f8aa3aadb7a8a.pdf&showname=1.2025%E5%B9%B410%E6%9C%88%E8%87%B312%E6%9C%88%E5%85%A8%E5%9B%BD%E4%BA%A7%E7%BD%91%E7%BB%9C%E5%89%A7%E7%89%87%E5%8F%91%E8%A1%8C%E8%AE%B8%E5%8F%AF%E6%83%85%E5%86%B5.pdf',
      releaseDate: '2026-01-10',
    },
  ],
  novel: [
    {
      title: '斗破苍穹',
      summary: '天蚕土豆创作的玄幻网文代表作，公开传播口径多按百亿级累计阅读量统计。',
      tags: ['玄幻', '网文', '爽文'],
      actors: ['天蚕土豆'],
      author: '天蚕土豆',
      ipName: '斗破苍穹',
      hotScore: 1_000_000,
      sourceUrl: 'https://www.cbish.com/xue/35826.html',
      releaseDate: '2009-04-14',
    },
    {
      title: '凡人修仙传',
      summary: '忘语创作的仙侠小说，“凡人流”开创文本，公开报道显示原著累计阅读量超百亿。',
      tags: ['仙侠', '修仙', '网文'],
      actors: ['忘语'],
      author: '忘语',
      ipName: '凡人修仙传',
      hotScore: 1_000_000,
      sourceUrl: 'https://finance.sina.cn/2025-08-21/detail-infmsqmp9833508.d.html?from=qudao',
      releaseDate: '2008-02-01',
    },
    {
      title: '全职高手',
      summary: '蝴蝶蓝创作的电竞网文代表作，公开传播口径多按百亿级累计阅读量归纳。',
      tags: ['电竞', '热血', '网文'],
      actors: ['蝴蝶蓝'],
      author: '蝴蝶蓝',
      ipName: '全职高手',
      hotScore: 1_000_000,
      sourceUrl: 'https://www.nbd.com.cn/rss/toutiao/articles/1358685.html',
      releaseDate: '2011-02-01',
    },
    {
      title: '诡秘之主',
      summary: '爱潜水的乌贼创作的蒸汽朋克奇幻网文，中文累计阅读量公开披露有限，这里按保守可确认口径入库。',
      tags: ['奇幻', '克苏鲁', '网文'],
      actors: ['爱潜水的乌贼'],
      author: '爱潜水的乌贼',
      ipName: '诡秘之主',
      hotScore: 10_000,
      sourceUrl: 'https://www.lomworld.com/zh/news/4',
      releaseDate: '2018-04-01',
    },
    {
      title: '三体',
      summary: '刘慈欣创作的中国科幻长篇，公开资料主要披露全球销量超过 3000 万册，累计阅读量待平台披露。',
      tags: ['科幻', '雨果奖', '硬科幻'],
      actors: ['刘慈欣'],
      author: '刘慈欣',
      ipName: '三体',
      hotScore: 0,
      sourceUrl: 'https://www.stdaily.com/web/gdxw/2025-08/24/content_389669.html',
      releaseDate: '2008-01-01',
    },
    {
      title: '庆余年',
      summary: '猫腻创作的架空历史小说，剧集热播期带动起点专区亿级流量，原著累计阅读量未公开披露。',
      tags: ['架空历史', '权谋', '网文'],
      actors: ['猫腻'],
      author: '猫腻',
      ipName: '庆余年',
      hotScore: 0,
      sourceUrl: 'https://news.cnhubei.com/content/2024-06/09/content_18025389.html',
      releaseDate: '2007-01-01',
    },
    {
      title: '盗墓笔记',
      summary: '南派三叔创作的冒险悬疑小说，公开资料主要披露实体书销量，累计阅读量待平台披露。',
      tags: ['悬疑', '冒险', '盗墓'],
      actors: ['南派三叔'],
      author: '南派三叔',
      ipName: '盗墓笔记',
      hotScore: 0,
      sourceUrl: 'https://www.chinanews.com.cn/cul/2011/11-24/3482487.shtml',
      releaseDate: '2006-07-01',
    },
    {
      title: '鬼吹灯',
      summary: '天下霸唱创作的探险小说，公开资料主要披露图书销量与读者群，累计阅读量待平台披露。',
      tags: ['探险', '悬疑', '民俗'],
      actors: ['天下霸唱'],
      author: '天下霸唱',
      ipName: '鬼吹灯',
      hotScore: 0,
      sourceUrl: 'https://media.people.com.cn/n/2015/0913/c40606-27576269.html',
      releaseDate: '2006-01-01',
    },
    {
      title: '大奉打更人',
      summary: '卖报小郎君创作的仙侠探案网文，公开资料披露剧集、有声和漫画表现较多，小说累计阅读量待平台披露。',
      tags: ['仙侠', '探案', '网文'],
      actors: ['卖报小郎君'],
      author: '卖报小郎君',
      ipName: '大奉打更人',
      hotScore: 0,
      sourceUrl: 'https://xueqiu.com/6899105006/362778550',
      releaseDate: '2020-06-01',
    },
    {
      title: '雪中悍刀行',
      summary: '烽火戏诸侯创作的武侠玄幻小说，公开资料多披露影视播放量与 IP 榜单，原著累计阅读量待平台披露。',
      tags: ['武侠', '玄幻', '网文'],
      actors: ['烽火戏诸侯'],
      author: '烽火戏诸侯',
      ipName: '雪中悍刀行',
      hotScore: 0,
      sourceUrl: 'https://www.jiemian.com/article/6983928.html',
      releaseDate: '2012-12-01',
    },
  ],
  comic: [
    {
      title: '一人之下',
      summary: '米二创作的国漫作品，以异人世界、炁体源流和张楚岚身世为核心展开。',
      tags: ['国漫', '异人', '热血'],
      actors: ['米二', '腾讯动漫'],
      author: '米二',
      ipName: '一人之下',
      hotScore: 3_000_000,
      sourceUrl: 'https://ac.qq.com/',
      releaseDate: '2015-02-01',
    },
    {
      title: '狐妖小红娘',
      summary: '小新创作的国漫，围绕人与妖的转世续缘故事展开。',
      tags: ['国漫', '奇幻', '恋爱'],
      actors: ['小新', '腾讯动漫'],
      author: '小新',
      ipName: '狐妖小红娘',
      hotScore: 1_660_000,
      sourceUrl: 'https://ac.qq.com/',
      releaseDate: '2012-06-01',
    },
    {
      title: '镖人',
      summary: '许先哲创作的硬派武侠漫画，以隋末西域镖客刀马的护送之路展开。',
      tags: ['国漫', '武侠', '历史'],
      actors: ['许先哲'],
      author: '许先哲',
      ipName: '镖人',
      hotScore: 0,
      sourceUrl: 'https://www.u17.com/',
      releaseDate: '2015-01-01',
    },
    {
      title: '非人哉',
      summary: '一汪空气创作的神仙妖怪日常漫画，把中国神话角色放入现代都市生活。',
      tags: ['国漫', '日常', '喜剧'],
      actors: ['一汪空气'],
      author: '一汪空气',
      ipName: '非人哉',
      hotScore: 3_000_000,
      sourceUrl: 'https://www.u17.com/',
      releaseDate: '2015-01-01',
    },
    {
      title: '中国惊奇先生',
      summary: '权迎升创作的都市奇幻漫画，讲述道法传人与现代都市灵异事件。',
      tags: ['国漫', '都市奇幻', '灵异'],
      actors: ['权迎升', '腾讯动漫'],
      author: '权迎升',
      ipName: '中国惊奇先生',
      hotScore: 3_000_000,
      sourceUrl: 'https://ac.qq.com/',
      releaseDate: '2013-06-01',
    },
    {
      title: '子不语',
      summary: '夏达创作的漫画作品，以少女与乡野奇异见闻构成清新灵异叙事。',
      tags: ['国漫', '灵异', '治愈'],
      actors: ['夏达'],
      author: '夏达',
      ipName: '子不语',
      hotScore: 0,
      sourceUrl: 'https://www.manhuatai.com/',
      releaseDate: '2008-01-01',
    },
    {
      title: '长歌行',
      summary: '夏达创作的历史漫画，讲述李长歌在唐初乱局中的成长与远行。',
      tags: ['国漫', '历史', '少女漫画'],
      actors: ['夏达'],
      author: '夏达',
      ipName: '长歌行',
      hotScore: 0,
      sourceUrl: 'https://www.manhuatai.com/',
      releaseDate: '2011-01-01',
    },
    {
      title: '端脑',
      summary: '壁水羽创作的科幻悬疑漫画，围绕高智商游戏与平行空间谜团展开。',
      tags: ['国漫', '科幻', '悬疑'],
      actors: ['壁水羽'],
      author: '壁水羽',
      ipName: '端脑',
      hotScore: 0,
      sourceUrl: 'https://ac.qq.com/',
      releaseDate: '2011-01-01',
    },
    {
      title: '雏蜂',
      summary: '白猫创作的近未来科幻漫画，以尖兵少女与军事科技冲突为主线。',
      tags: ['国漫', '科幻', '动作'],
      actors: ['白猫'],
      author: '白猫',
      ipName: '雏蜂',
      hotScore: 0,
      sourceUrl: 'https://www.u17.com/',
      releaseDate: '2010-01-01',
    },
    {
      title: '镇魂街',
      summary: '许辰创作的热血漫画，讲述寄灵人与守护灵在镇魂街世界中的战斗。',
      tags: ['国漫', '热血', '奇幻'],
      actors: ['许辰'],
      author: '许辰',
      ipName: '镇魂街',
      hotScore: 503_600,
      sourceUrl: 'https://www.u17.com/',
      releaseDate: '2010-01-01',
    },
  ],
  anime: [
    {
      title: '凡人修仙传',
      summary: '国产 3D 动画，改编自忘语同名小说，讲述韩立从凡人踏入修仙世界。',
      tags: ['国产动画', '修仙', '3D'],
      actors: ['钱文青', '杨天翔', '佟心竹'],
      author: '万维猫动画',
      ipName: '凡人修仙传',
      hotScore: 610_000,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2020-07-25',
    },
    {
      title: '灵笼',
      summary: '艺画开天制作的原创国产科幻动画，描绘末世灯塔文明与地面生态危机。',
      tags: ['国产动画', '科幻', '末世'],
      actors: ['黄莺', '李元韬', '陶典'],
      author: '艺画开天',
      ipName: '灵笼',
      hotScore: 1_000_000,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2019-07-13',
    },
    {
      title: '中国奇谭',
      summary: '上海美术电影制片厂与哔哩哔哩联合出品的动画短片集，重塑中国志怪与民俗想象。',
      tags: ['国产动画', '短片集', '志怪'],
      actors: ['上海美术电影制片厂', '哔哩哔哩'],
      author: '上海美术电影制片厂',
      ipName: '中国奇谭',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2023-01-01',
    },
    {
      title: '时光代理人',
      summary: 'LAN Studio 制作的原创国产动画，以照片委托和时间回溯展开悬疑单元故事。',
      tags: ['国产动画', '悬疑', '原创'],
      actors: ['苏尚卿', '杨天翔', '李诗萌'],
      author: 'LAN Studio',
      ipName: '时光代理人',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2021-04-30',
    },
    {
      title: '雾山五行',
      summary: '六道无鱼工作室制作的国产动画，以水墨风格呈现五行使者与妖兽冲突。',
      tags: ['国产动画', '水墨', '动作'],
      actors: ['郭盛', '郝祥海', '叶知秋'],
      author: '六道无鱼工作室',
      ipName: '雾山五行',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2020-07-26',
    },
    {
      title: '斗罗大陆',
      summary: '玄机科技制作的国产 3D 动画，公开平台累计播放量按 538 亿+ 口径统计。',
      tags: ['国产动画', '玄幻', '3D'],
      actors: ['沈磊', '程玉珠', '黄翔宇'],
      author: '玄机科技',
      ipName: '斗罗大陆',
      hotScore: 5_380_000,
      sourceUrl: 'https://v.qq.com/',
      releaseDate: '2018-01-20',
    },
    {
      title: '遮天',
      summary: '腾讯视频出品的国产 3D 动画，公开平台累计播放量按 1700 亿+ 口径统计。',
      tags: ['国产动画', '玄幻', '3D'],
      actors: ['徐翔', '赵乾景'],
      author: '腾讯视频',
      ipName: '遮天',
      hotScore: 17_000_000,
      sourceUrl: 'https://v.qq.com/',
      releaseDate: '2023-05-03',
    },
    {
      title: '大理寺日志',
      summary: '好传动画制作的国产动画，讲述唐代大理寺众人在奇案中的冒险。',
      tags: ['国产动画', '历史', '悬疑'],
      actors: ['郭盛', '翟昱霖', '皇贞季'],
      author: '好传动画',
      ipName: '大理寺日志',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2020-04-10',
    },
    {
      title: '罗小黑战记',
      summary: 'MTJJ 创作的国产动画系列，以妖精小黑在人类社会中的成长与归属为核心。',
      tags: ['国产动画', '奇幻', '治愈'],
      actors: ['山新', '皇贞季', '琪琪'],
      author: 'MTJJ',
      ipName: '罗小黑战记',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2011-03-17',
    },
    {
      title: '天官赐福',
      summary: '绘梦动画制作的国产动画，改编自墨香铜臭小说，讲述谢怜与花城的仙乐奇缘。',
      tags: ['国产动画', '奇幻', '小说改编'],
      actors: ['姜广涛', '马正阳', '黄莺'],
      author: '绘梦动画',
      ipName: '天官赐福',
      hotScore: 0,
      sourceUrl: 'https://www.bilibili.com/bangumi/',
      releaseDate: '2020-10-31',
    },
    {
      title: '魔道祖师',
      summary: '视美影业制作的国产动画，改编自墨香铜臭小说，讲述魏无羡与蓝忘机追查旧案。',
      tags: ['国产动画', '奇幻', '小说改编'],
      actors: ['张杰', '边江', '郭浩然'],
      author: '视美影业',
      ipName: '魔道祖师',
      hotScore: 0,
      sourceUrl: 'https://v.qq.com/',
      releaseDate: '2018-07-09',
    },
  ],
};

const CURATED_REAL_TITLES_BY_TYPE = new Map(
  Object.entries(CURATED_REAL_CONTENTS).map(([type, items]) => [
    type,
    new Set(items.map(item => item.title)),
  ])
);

function isCuratedRealSeedEnabled(value = process.env.MEDIAHUB_CURATED_REAL_SEED_ENABLED) {
  const normalized = String(value ?? '').trim().toLowerCase();
  if (!normalized) return true;
  return ['1', 'true', 'yes', 'on'].includes(normalized);
}

function buildCuratedId(type, title) {
  const hash = createHash('sha1').update(`${type}:${title}`).digest('hex').slice(0, 12);
  return `${type}:curated-cn:${hash}`;
}

function buildCuratedRealContents(type) {
  return (CURATED_REAL_CONTENTS[type] || []).map(item => normalizeContent({
    id: buildCuratedId(type, item.title),
    title: item.title,
    summary: item.summary,
    type,
    tags: item.tags,
    actors: item.actors,
    author: item.author,
    ipName: item.ipName,
    status: 'completed',
    hotScore: item.hotScore,
    createdAt: item.releaseDate,
    updatedAt: item.releaseDate,
    source: {
      ...SOURCE,
      url: item.sourceUrl,
    },
  }));
}

function isCurrentCuratedChinaTitle(type, title) {
  return Boolean(CURATED_REAL_TITLES_BY_TYPE.get(type)?.has(title));
}

function getCuratedChinaFilterPairs() {
  return [...CURATED_REAL_TITLES_BY_TYPE.entries()].flatMap(([type, titles]) => (
    [...titles].map(title => ({ type, title }))
  ));
}

function seedCuratedRealContents(type) {
  const list = buildCuratedRealContents(type);
  if (list.length === 0) return { count: 0, list };
  return {
    count: upsertContents(list),
    list,
  };
}

export {
  buildCuratedRealContents,
  getCuratedChinaFilterPairs,
  isCuratedRealSeedEnabled,
  isCurrentCuratedChinaTitle,
  seedCuratedRealContents,
};
