import { normalizeCountMetric } from './realMetricCollectorService.js';

const FIELD_NAMES = new Set(['releaseDate', 'playCount', 'readCount', 'contentType', 'actors', 'copyrightOwner', 'summary']);
const SOURCE_TYPE_PRIORITY = { official_media: 0, platform_public: 1, trusted_third_party: 2, self_media: 3 };
const FIELD_LABELS = { releaseDate: '上线时间', playCount: '播放量', readCount: '阅读量', contentType: '类型', actors: '主演', copyrightOwner: '版权方', summary: '简介' };

const PLAY_RE = /(?:\u5168\u7f51\u6709\u6548\u64ad\u653e\u91cf|\u7d2f\u8ba1\u64ad\u653e\u91cf|\u603b\u64ad\u653e\u91cf|\u64ad\u653e\u91cf|\u64ad\u653e|\u89c2\u770b)\s*(?:\u7a81\u7834|\u7834|\u8fbe|\u8fbe\u5230|\u8d85|\u8d85\u8fc7|\u4e3a|\u7ea6|:|\uFF1A)?\s*([0-9]+(?:\.[0-9]+)?\s*(?:\u4ebf|\u4e07|\u5343|\u6b21)?)/i;
const READ_RE = /(?:\u7d2f\u8ba1\u9605\u8bfb\u91cf|\u603b\u9605\u8bfb\u91cf|\u603b\u9605\u8bfb|\u9605\u8bfb\u91cf|\u9605\u8bfb)\s*(?:\u7a81\u7834|\u7834|\u8fbe|\u8fbe\u5230|\u8d85|\u8d85\u8fc7|\u4e3a|\u7ea6|:|\uFF1A)?\s*([0-9]+(?:\.[0-9]+)?\s*(?:\u4ebf|\u4e07|\u5343|\u6b21)?)/i;
const HEAT_CONTEXT_RE = /(?:热度|热力|指数|排名|榜单|月票|推荐票|点赞|收藏|评论|弹幕|搜索|话题)/;

function cleanText(value, fallback = '') { return String(value || fallback).replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(); }
function stripBookMarks(value) { return cleanText(value).replace(/^《(.+)》$/, '$1').trim(); }
function normalizeCapturedAt(now = new Date()) { const date = now instanceof Date ? now : new Date(now || Date.now()); return Number.isNaN(date.getTime()) ? new Date().toISOString() : date.toISOString(); }
function pad2(value) { return String(value).padStart(2, '0'); }
function normalizeDate(value) {
  const text = cleanText(value);
  let match = text.match(/(20\d{2}|19\d{2})[年\-\/\.](\d{1,2})[月\-\/\.](\d{1,2})日?/);
  if (match) return `${match[1]}-${pad2(match[2])}-${pad2(match[3])}`;
  match = text.match(/(20\d{2}|19\d{2})(\d{2})(\d{2})/);
  if (match) return `${match[1]}-${match[2]}-${match[3]}`;
  match = text.match(/(20\d{2}|19\d{2})[年\-\/\.](\d{1,2})月?/);
  if (match) return `${match[1]}-${pad2(match[2])}-01`;
  return '';
}
function splitList(value, max = 8) {
  return [...new Set(trimFieldValue(value, 160)
    .replace(/[等及领衔主演特别出演友情出演联合主演]/g, ' ')
    .split(/[、,，\/｜|·和与\s]+/)
    .map(item => stripBookMarks(item))
    .filter(item => item && item.length <= 20 && /[一-鿿A-Za-z]/.test(item)))]
    .slice(0, max);
}
const NEXT_FIELD_BOUNDARY_RE = /[\uFF0C,]\s*(?=(?:\u4e0a\u7ebf\u65f6\u95f4|\u64ad\u51fa\u65f6\u95f4|\u5f00\u64ad\u65f6\u95f4|\u9996\u64ad\u65f6\u95f4|\u53d1\u5e03\u65f6\u95f4|\u7c7b\u578b|\u9898\u6750|\u54c1\u7c7b|\u5206\u7c7b|\u4e3b\u6f14|\u9886\u8854\u4e3b\u6f14|\u6f14\u5458\u9635\u5bb9|\u7248\u6743\u65b9|\u7248\u6743\u6240\u6709|\u51fa\u54c1\u65b9|\u5236\u4f5c\u65b9|\u53d1\u884c\u65b9|\u5907\u6848\u673a\u6784|\u7b80\u4ecb|\u5267\u60c5\u7b80\u4ecb|\u7d2f\u8ba1\u64ad\u653e\u91cf|\u603b\u64ad\u653e\u91cf|\u64ad\u653e\u91cf|\u7d2f\u8ba1\u9605\u8bfb\u91cf|\u9605\u8bfb\u91cf)\s*(?:\u4e3a|\u662f|\u7cfb|:|\uFF1A)?)/;
function trimFieldValue(value, max = 120) {
  let text = cleanText(value).replace(/^(?:为|是|系|由|于|在|已|正式|宣布|显示|称|介绍|：|:|，|,|。)+/, '').trim();
  text = text.split(NEXT_FIELD_BOUNDARY_RE)[0];
  text = text.replace(/[\u3002\uFF1B;].*$/, '').trim();
  return text.slice(0, max);
}
function normalizeSourceType(value = '') { const normalized = String(value || '').trim(); return ['official_media', 'self_media', 'platform_public', 'trusted_third_party'].includes(normalized) ? normalized : 'self_media'; }
function sourceConfidenceFromType(sourceType) { return sourceType === 'official_media' || sourceType === 'platform_public' ? 'high' : 'medium'; }
function metricConfidenceFromType(sourceType) { return sourceType === 'official_media' || sourceType === 'platform_public' ? 'official' : 'trusted_third_party'; }
function buildFieldSource({ field, value, sourceId, sourceName, sourceUrl, sourceType, capturedAt, snippet }) {
  if (!FIELD_NAMES.has(field)) return null;
  if (value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0)) return null;
  const normalizedSourceType = normalizeSourceType(sourceType);
  return { field, value, sourceId: cleanText(sourceId, 'public_report').toLowerCase(), sourceName: cleanText(sourceName, '公开报道'), sourceUrl: cleanText(sourceUrl), sourceType: normalizedSourceType, capturedAt, confidence: sourceConfidenceFromType(normalizedSourceType), snippet: cleanText(snippet).slice(0, 180) };
}
function findSnippet(text, index, length = 120) { if (index < 0) return cleanText(text).slice(0, length); const start = Math.max(0, index - 40); return cleanText(String(text || '').slice(start, index + length)); }
function collectRegexSources({ text, source, field, regex, valueBuilder }) { const sources = []; let match; const re = new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : `${regex.flags}g`); while ((match = re.exec(text))) { const built = buildFieldSource({ ...source, field, value: valueBuilder(match), snippet: findSnippet(text, match.index) }); if (built) sources.push(built); } return sources; }
function extractMetricSource({ text, source, field, regex, metricType }) { const sources = []; let match; const re = new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : `${regex.flags}g`); while ((match = re.exec(text))) { const snippet = findSnippet(text, match.index); const nearContext = String(text || '').slice(Math.max(0, match.index - 12), match.index + match[0].length + 4); if (/(?:\u8bdd\u9898|\u641c\u7d22|\u70ed\u641c|\u6307\u6570)/.test(nearContext)) continue; if (HEAT_CONTEXT_RE.test(snippet) && !(metricType === 'play' ? /\u64ad\u653e|\u89c2\u770b/.test(match[0]) : /\u9605\u8bfb/.test(match[0]))) continue; const value = normalizeCountMetric(match[0]) || normalizeCountMetric(`${FIELD_LABELS[field]} ${match[1]}`); const built = buildFieldSource({ ...source, field, value, snippet }); if (built) sources.push(built); } return sources; }

function extractPublicReportFieldsFromText({ text, sourceId = 'public_report', sourceName = '公开报道', sourceUrl = '', sourceType = 'self_media', capturedAt, now = new Date() } = {}) {
  const body = cleanText(text); if (!body) return [];
  const source = { sourceId, sourceName, sourceUrl, sourceType, capturedAt: capturedAt || normalizeCapturedAt(now) };
  const sources = [];
  sources.push(...collectRegexSources({ text: body, source, field: 'releaseDate', regex: /(?:上线时间|播出时间|开播时间|首播时间|发布时间|定档(?:时间)?|上线|开播|首播)\s*(?:为|于|在|:|：)?\s*((?:20\d{2}|19\d{2})[年\-\/\.](?:\d{1,2})(?:[月\-\/\.](?:\d{1,2})日?)?)/i, valueBuilder: match => normalizeDate(match[1]) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'contentType', regex: /(?:类型|题材|品类|分类)\s*(?:为|是|系|:|：)\s*([^。；;\n]{2,40})/i, valueBuilder: match => trimFieldValue(match[1], 40) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'actors', regex: /(?:主演|领衔主演|演员阵容)\s*(?:为|是|包括|:|：)?\s*([^。；;\n]{2,80})/i, valueBuilder: match => splitList(match[1]) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'actors', regex: /由\s*([^。；;\n]{2,80}?)\s*(?:主演|领衔主演)/i, valueBuilder: match => splitList(match[1]) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'copyrightOwner', regex: /(?:版权方|版权所有|版权归属|出品方|制作方|发行方|备案机构|版权公司)\s*(?:为|是|系|:|：)?\s*([^。；;\n]{2,60})/i, valueBuilder: match => trimFieldValue(match[1], 60) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'summary', regex: /(?:简介|剧情简介|剧情介绍|故事简介|内容简介)\s*(?:为|是|:|：)?\s*([^\n]{8,220})/i, valueBuilder: match => trimFieldValue(match[1], 220) }));
  sources.push(...collectRegexSources({ text: body, source, field: 'summary', regex: /(讲述了[^。；;\n]{8,220})/i, valueBuilder: match => trimFieldValue(match[1], 220) }));
  sources.push(...extractMetricSource({ text: body, source, field: 'playCount', regex: PLAY_RE, metricType: 'play' }));
  sources.push(...extractMetricSource({ text: body, source, field: 'readCount', regex: READ_RE, metricType: 'read' }));
  return dedupeFieldSources(sources);
}

function extractPublicReportFieldsFromJson({ json, sourceId, sourceName, sourceUrl, sourceType, capturedAt, now = new Date() } = {}) {
  if (!json || typeof json !== 'object') return [];
  const source = { sourceId, sourceName, sourceUrl, sourceType, capturedAt: capturedAt || normalizeCapturedAt(now) };
  const sources = []; const push = (field, value, snippet = '') => { const built = buildFieldSource({ ...source, field, value, snippet }); if (built) sources.push(built); };
  const walk = (node) => { if (!node || typeof node !== 'object') return; if (Array.isArray(node)) { node.forEach(item => walk(item)); return; } for (const [key, value] of Object.entries(node)) { const compact = key.replace(/[_\-\s]/g, '').toLowerCase(); if (typeof value === 'string' || typeof value === 'number') { if (/releasedate|publishtime|onlinetime|airtime|上线|开播|发布时间/.test(compact)) push('releaseDate', normalizeDate(value), key); else if (/category|genre|题材|类型|分类/.test(compact)) push('contentType', trimFieldValue(value, 40), key); else if (/copyright|owner|producer|publisher|版权|出品|制作|发行|备案/.test(compact)) push('copyrightOwner', trimFieldValue(value, 60), key); else if (/summary|intro|description|简介|剧情/.test(compact)) push('summary', trimFieldValue(value, 220), key); else if (/playcount|viewcount|播放/.test(compact) && !/heat|rank|score|like|favorite|comment/.test(compact)) push('playCount', normalizeCountMetric(value), key); else if (/readcount|readingcount|阅读/.test(compact) && !/heat|rank|score|like|favorite|comment/.test(compact)) push('readCount', normalizeCountMetric(value), key); } if (Array.isArray(value) && /actor|cast|主演|演员/.test(compact)) push('actors', splitList(value.join('、')), key); else walk(value); } };
  walk(json); return dedupeFieldSources(sources);
}
function dedupeFieldSources(sources = []) { const map = new Map(); for (const source of sources) { if (!source || !FIELD_NAMES.has(source.field)) continue; const valueKey = Array.isArray(source.value) ? source.value.join('|') : String(source.value); const key = `${source.field}|${valueKey}|${source.sourceUrl || source.sourceId}`; if (!map.has(key)) map.set(key, source); } return [...map.values()]; }
function compareFieldSource(a, b) { const confidenceDiff = (a.confidence === 'high' ? 0 : 1) - (b.confidence === 'high' ? 0 : 1); if (confidenceDiff !== 0) return confidenceDiff; const sourceDiff = (SOURCE_TYPE_PRIORITY[a.sourceType] ?? 9) - (SOURCE_TYPE_PRIORITY[b.sourceType] ?? 9); if (sourceDiff !== 0) return sourceDiff; const aSize = Array.isArray(a.value) ? a.value.length : String(a.value || '').length; const bSize = Array.isArray(b.value) ? b.value.length : String(b.value || '').length; if (bSize !== aSize) return bSize - aSize; const dateDiff = Date.parse(b.capturedAt || '') - Date.parse(a.capturedAt || ''); if (Number.isFinite(dateDiff) && dateDiff !== 0) return dateDiff; return 0; }
function dedupeMetricSources(sources = []) { const map = new Map(); for (const source of sources) { if (!source || !Number.isFinite(Number(source.value))) continue; const key = `${source.metricType}|${source.value}|${source.sourceUrl || source.sourceId}`; if (!map.has(key)) map.set(key, source); } return [...map.values()]; }
function mergeFieldSources(existing = [], next = []) { return dedupeFieldSources([...(Array.isArray(existing) ? existing : []), ...(Array.isArray(next) ? next : [])]); }
function selectPublicReportFieldPatch(sources = [], item = {}) { const validSources = dedupeFieldSources(sources).filter(source => source && FIELD_NAMES.has(source.field)); const byField = new Map(); for (const source of validSources) { if (!byField.has(source.field)) byField.set(source.field, []); byField.get(source.field).push(source); } const selectedSources = []; const selected = (field) => { const list = (byField.get(field) || []).sort(compareFieldSource); if (list[0]) selectedSources.push(list[0]); return list[0]; }; const patch = {}; const releaseDate = selected('releaseDate'); if (releaseDate) patch.releaseDate = releaseDate.value; const contentType = selected('contentType'); if (contentType) patch.contentType = contentType.value; const actors = selected('actors'); if (actors) patch.actors = actors.value; const copyrightOwner = selected('copyrightOwner'); if (copyrightOwner) patch.copyrightOwner = copyrightOwner.value; const summary = selected('summary'); if (summary) patch.summary = summary.value; const play = selected('playCount'); const read = selected('readCount'); if (play || read) { const existingMetricSources = Array.isArray(item?.metrics?.realMetricSources) ? item.metrics.realMetricSources : []; const realMetricSources = [...existingMetricSources]; for (const metric of [play, read].filter(Boolean)) realMetricSources.push({ sourceId: metric.sourceId, sourceName: metric.sourceName, sourceUrl: metric.sourceUrl, metricType: metric.field === 'readCount' ? 'read' : 'play', value: Number(metric.value), unit: 'count', method: metric.sourceType === 'trusted_third_party' ? 'third_party' : 'public_page', confidence: metricConfidenceFromType(metric.sourceType), capturedAt: metric.capturedAt }); const preferred = item?.heatMetric === 'reading' || item?.type === 'novel' || item?.type === 'comic' ? read : play; patch.metrics = { ...(item?.metrics || {}), realMetricSources: dedupeMetricSources(realMetricSources), realMetricStatus: preferred ? metricConfidenceFromType(preferred.sourceType) : item?.metrics?.realMetricStatus, realMetricCapturedAt: preferred?.capturedAt || item?.metrics?.realMetricCapturedAt }; if (play) patch.metrics.realPlayCount = Number(play.value); if (read) patch.metrics.realReadCount = Number(read.value); } if (contentType?.value) { const tags = Array.isArray(item?.tags) ? item.tags : (Array.isArray(item?.categories) ? item.categories : []); patch.tags = [...new Set([contentType.value, ...tags].filter(Boolean))].slice(0, 8); } patch.fieldSources = mergeFieldSources(item?.fieldSources, selectedSources); return patch; }
function normalizeReportCandidate(candidate = {}, base = {}) { const sourceId = cleanText(candidate.sourceId || candidate.id || candidate.provider || base.sourceId || 'public_report').toLowerCase(); const sourceUrl = cleanText(candidate.sourceUrl || candidate.url || base.sourceUrl); return { sourceId, sourceName: cleanText(candidate.sourceName || candidate.label || base.sourceName || sourceId, '公开报道'), sourceUrl, sourceType: normalizeSourceType(candidate.sourceType || candidate.type || base.sourceType), text: candidate.text || candidate.html || candidate.snippet || '', json: candidate.json }; }
function getPublicReportSourceCandidates(item = {}, options = {}) { const source = typeof item?.source === 'object' ? item.source : {}; const base = { sourceId: source.provider || item?.source || item?.sourceId || 'public_report', sourceName: source.label || item?.sourceName || '公开报道', sourceUrl: source.url || item?.sourceUrl || item?.url || '', sourceType: 'platform_public' }; const candidates = [normalizeReportCandidate({ ...base, text: [item?.summary, item?.description].filter(Boolean).join(' ') }, base)]; const extra = [...(Array.isArray(item?.publicReportSourceCandidates) ? item.publicReportSourceCandidates : []), ...(Array.isArray(options.sourceCandidates) ? options.sourceCandidates : [])]; for (const candidate of extra) candidates.push(normalizeReportCandidate(candidate, base)); return candidates.filter(candidate => candidate.text || candidate.json || candidate.sourceUrl); }
async function collectPublicReportFieldsForItem({ item, fetchText, fetchJson, searchPublicReports, now = new Date(), sourceCandidates = [] } = {}) { const capturedAt = normalizeCapturedAt(now); const candidates = getPublicReportSourceCandidates(item, { sourceCandidates }); if (typeof searchPublicReports === 'function') { const reports = await searchPublicReports({ title: item?.title || '', type: item?.type || '', fields: [...FIELD_NAMES], item }); for (const report of Array.isArray(reports) ? reports : []) candidates.push(normalizeReportCandidate(report)); } const sources = []; const errors = []; for (const candidate of candidates) { try { if (candidate.text) sources.push(...extractPublicReportFieldsFromText({ ...candidate, capturedAt, now, text: candidate.text })); if (candidate.json) sources.push(...extractPublicReportFieldsFromJson({ ...candidate, capturedAt, now, json: candidate.json })); if (candidate.sourceUrl && typeof fetchText === 'function' && !candidate.text) { const text = await fetchText(candidate.sourceUrl, { item, candidate }); sources.push(...extractPublicReportFieldsFromText({ ...candidate, capturedAt, now, text })); } if (candidate.sourceUrl && typeof fetchJson === 'function' && !candidate.json) { const json = await fetchJson(candidate.sourceUrl, { item, candidate }); sources.push(...extractPublicReportFieldsFromJson({ ...candidate, capturedAt, now, json })); } } catch (error) { errors.push({ sourceId: candidate.sourceId, sourceUrl: candidate.sourceUrl, message: error?.message || 'public report collection failed' }); } } return { patch: selectPublicReportFieldPatch(sources, item), sources: dedupeFieldSources(sources), errors }; }
async function enrichItemsWithPublicReportFields(items = [], options = {}) { const list = []; const errors = []; for (const item of items) { try { const result = await collectPublicReportFieldsForItem({ item, ...options }); list.push({ ...item, ...result.patch, metrics: result.patch.metrics || item.metrics }); errors.push(...result.errors.map(error => ({ ...error, id: item?.id || '', title: item?.title || '' }))); } catch (error) { errors.push({ id: item?.id || '', title: item?.title || '', message: error?.message || 'public report collection failed' }); list.push(item); } } return { list, errors }; }
export { FIELD_LABELS, collectPublicReportFieldsForItem, enrichItemsWithPublicReportFields, extractPublicReportFieldsFromJson, extractPublicReportFieldsFromText, getPublicReportSourceCandidates, normalizeDate, selectPublicReportFieldPatch };
